"""changes category_id to category

Revision ID: 1be654018f84
Revises: 5a399490db45
Create Date: 2019-10-23 20:40:08.542371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1be654018f84'
down_revision = '5a399490db45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pitches_category_fkey', 'pitches', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('pitches_category_fkey', 'pitches', 'category', ['category'], ['id'])
    # ### end Alembic commands ###
