"""changes in pitches

Revision ID: 2e9f41c8acc9
Revises: 62eb7b69cef5
Create Date: 2019-10-24 09:34:13.318873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e9f41c8acc9'
down_revision = '62eb7b69cef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comments_comment_post', table_name='comments')
    op.drop_table('comments')
    op.drop_index('ix_category_name', table_name='category')
    op.drop_table('category')
    op.add_column('pitches', sa.Column('pitch', sa.String(length=300), nullable=True))
    op.add_column('pitches', sa.Column('title', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_pitches_pitch'), 'pitches', ['pitch'], unique=False)
    op.create_index(op.f('ix_pitches_title'), 'pitches', ['title'], unique=False)
    op.drop_index('ix_pitches_description', table_name='pitches')
    op.drop_index('ix_pitches_name', table_name='pitches')
    op.drop_constraint('pitches_comments_id_fkey', 'pitches', type_='foreignkey')
    op.drop_constraint('pitches_category_fkey', 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'category')
    op.drop_column('pitches', 'description')
    op.drop_column('pitches', 'comments_id')
    op.drop_column('pitches', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('comments_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pitches_category_fkey', 'pitches', 'category', ['category'], ['id'])
    op.create_foreign_key('pitches_comments_id_fkey', 'pitches', 'comments', ['comments_id'], ['id'])
    op.create_index('ix_pitches_name', 'pitches', ['name'], unique=False)
    op.create_index('ix_pitches_description', 'pitches', ['description'], unique=False)
    op.drop_index(op.f('ix_pitches_title'), table_name='pitches')
    op.drop_index(op.f('ix_pitches_pitch'), table_name='pitches')
    op.drop_column('pitches', 'title')
    op.drop_column('pitches', 'pitch')
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('category_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='category_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_category_name', 'category', ['name'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('comment_post', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], name='comments_pitch_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='comments_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='comments_pkey')
    )
    op.create_index('ix_comments_comment_post', 'comments', ['comment_post'], unique=False)
    # ### end Alembic commands ###
