"""changes category_id back to category

Revision ID: 76e0e9f35213
Revises: 1be654018f84
Create Date: 2019-10-23 20:49:48.240691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76e0e9f35213'
down_revision = '1be654018f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_pitches_category'), 'pitches', ['category'], unique=False)
    op.create_foreign_key(None, 'pitches', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_index(op.f('ix_pitches_category'), table_name='pitches')
    op.drop_column('pitches', 'category_id')
    # ### end Alembic commands ###
