"""Creates pitches in the db with category and title and content 

Revision ID: c6a5a0c1b385
Revises: 3283059a2b24
Create Date: 2019-10-22 06:05:29.993463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6a5a0c1b385'
down_revision = '3283059a2b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'category')
    # ### end Alembic commands ###
